/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        title: 'rgba(var(--title))',
        titleH: 'rgba(var(--title-h))',
        paragraph: 'rgba(var(--paragraph))',
        textWhite: 'rgba(var(--text-white))',
        textSecondary: 'rgba(var(--text-secondary))',
        containerBg: 'rgba(var(--container-bg))',
        smBtnBg: 'rgba(var(--sm-btn-bg))',
        smBtnBgA:  'rgba(var(--sm-btn-bg-a))',
        smBtnBgH:  'rgba(var(--sm-btn-bg-h))',
        smBtnTxt:  'rgba(var(--sm-btn-txt))',
        smBtnTxtA:  'rgba(var(--sm-btn-txt-a))',
        view:  'rgba(var(--view))',
        viewA:  'rgba(var(--view-a))',
        viewD:  'rgba(var(--view-d))',
        roadNums:  'rgba(var(--road-nums))',
        arrow:  'rgba(var(--arrow))',
        arrowA:  'rgba(var(--arrow-a))',
        nums:  'rgba(var(--nums))',
        numsA:  'rgba(var(--nums-a))',
        orange:  'rgba(var(--orange))',
        purple:  'rgba(var(--purple))',
        cyan:  'rgba(var(--cyan))',
        headerBg:  'rgba(var(--header-bg))',
        addBtn:  'rgba(var(--add-btn))',
        addBtnH:  'rgba(var(--add-btn-h))',
        editBtn:  'rgba(var(--edit-btn))',
        editBtnH:  'rgba(var(--edit-btn-h))',
        cancelBtn:  'rgba(var(--cancel-btn))',
        cancelBtnH:  'rgba(var(--cancel-btn-h))',
        deleteBtn:  'rgba(var(--delete-btn))',
        deleteBtnH:  'rgba(var(--delete-btn-h))',
        goBackBtn:  'rgba(var(--go-back-btn))',
        inputBg:  'rgba(var(--input-bg))',
        inputBorderS:  'rgba(var(--input-border-s))',
        inputBorderE:  'rgba(var(--input-border-e))',
        },
      screens: {
        mobile: "375px",
        tablet: "768px",
        desktop: "1440px",
      },
    },
  },
  plugins: [],
  darkMode: "class",
}